apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fb-metadata-api-cron-remove-acceptance-services-{{ .Values.environmentName }}
  namespace: formbuilder-saas-{{ .Values.environmentName }}
spec:
  schedule: "0 6 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            remove-acceptance-tests-services: cronjob
        spec:
          containers:
          - name: "fb-metadata-api-{{ .Values.environmentName }}"
            image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-metadata-api:{{ .Values.circleSha1 }}"
            args:
            - /bin/sh
            - -c
            - bundle exec rails remove_acceptance_tests_services
            securityContext:
              runAsUser: 1001
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: fb-metadata-api-config-map
            env:
              - name: SECRET_KEY_BASE
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                    key: secret_key_base
              - name: ENCODED_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                    key: encoded_private_key
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: rds-instance-formbuilder-metadata-api-{{ .Values.environmentName }}
                    key: url
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: fb-metadata-api-secrets-{{ .Values.environmentName }}
                    key: sentry_dsn
              - name: PLATFORM_ENV
                value: {{ .Values.environmentName }}
          restartPolicy: Never
